orb-mcu-util: don't fail on building boards object
worldcoin/orb-software pull request #136
Opened 2024-06-14 07:28 UTC by fouge

heartbeat is sent to check that mcu is alive
but if it's not, don't fail because the command
might be targeted to the other MCU

- [ ] huge backtrace though, make error cleaner

```
2024-06-14T07:11:10.506191Z ERROR orb_mcu_util::orb::main_board: Failed to send heartbeat to main mcu:
   0: ack not received (raw)
   1: deadline has elapsed

Location:
   mcu-interface/src/can/canfd.rs:111

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 5 frames hidden ⋮
   6: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual::hb79dbcd894564f88
      at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/result.rs:1959
   7: orb_mcu_interface::can::canfd::CanRawMessaging::wait_ack::{{closure}}::{{closure}}::ha7e5dd4127e55238
      at /Users/cyril.fougeray/Documents/worldcoin/orb-software/mcu-interface/src/can/canfd.rs:111
   8: <T as futures_util::fns::FnOnce1<A>>::call_once::h63025e665e3ae151
      at /Users/cyril.fougeray/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/fns.rs:15
   9: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h84d4a165739e6094
      at /Users/cyril.fougeray/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/future/map.rs:57
  10: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::hb7ee6b399396ccb5
      at /Users/cyril.fougeray/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/lib.rs:91
  11: orb_mcu_interface::can::canfd::CanRawMessaging::wait_ack::{{closure}}::h7964d1620d842d5d
      at /Users/cyril.fougeray/Documents/worldcoin/orb-software/mcu-interface/src/can/canfd.rs:112
  12: orb_mcu_interface::can::canfd::CanRawMessaging::send_wait_ack::{{closure}}::h1d6a3148098b7146
      at /Users/cyril.fougeray/Documents/worldcoin/orb-software/mcu-interface/src/can/canfd.rs:136
  13: <orb_mcu_interface::can::canfd::CanRawMessaging as orb_mcu_interface::MessagingInterface>::send::{{closure}}::hc7049020c3198327
      at /Users/cyril.fougeray/Documents/worldcoin/orb-software/mcu-interface/src/can/canfd.rs:265
  14: <core::pin::Pin<P> as core::future::future::Future>::poll::ha11dc2bb3b80f343
      at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/future/future.rs:124
  15: orb_mcu_util::orb::main_board::MainBoardBuilder::build::{{closure}}::hd4046c709148b1c3
      at /Users/cyril.fougeray/Documents/worldcoin/orb-software/mcu-util/src/orb/main_board.rs:77
  16: orb_mcu_util::orb::Orb::new::{{closure}}::h302a02f5558fe731
      at /Users/cyril.fougeray/Documents/worldcoin/orb-software/mcu-util/src/orb/mod.rs:63
  17: orb_mcu_util::execute::{{closure}}::h52a309bd39857a6e
      at /Users/cyril.fougeray/Documents/worldcoin/orb-software/mcu-util/src/main.rs:125
  18: orb_mcu_util::main::{{closure}}::ha7ec7c18918e7e08
      at /Users/cyril.fougeray/Documents/worldcoin/orb-software/mcu-util/src/main.rs:206
  19: tokio::runtime::park::CachedParkThread::block_on::{{closure}}::h1722bf4ca283899d
      at /Users/cyril.fougeray/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/park.rs:281
  20: tokio::runtime::coop::with_budget::ha0140bc0066fe0e0
      at /Users/cyril.fougeray/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/coop.rs:107
  21: tokio::runtime::coop::budget::h35c8f0553e05987b
      at /Users/cyril.fougeray/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/coop.rs:73
  22: tokio::runtime::park::CachedParkThread::block_on::hb5e55ce5bd1c63ee
      at /Users/cyril.fougeray/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/park.rs:281
  23: tokio::runtime::context::blocking::BlockingRegionGuard::block_on::h126aa30da1ec387a
      at /Users/cyril.fougeray/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/context/blocking.rs:66
  24: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}::hd3afc48634f38bb5
      at /Users/cyril.fougeray/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/multi_thread/mod.rs:87
  25: tokio::runtime::context::runtime::enter_runtime::h332170828e9058c1
      at /Users/cyril.fougeray/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/context/runtime.rs:65
  26: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::hc02d16b46f00f758
      at /Users/cyril.fougeray/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/multi_thread/mod.rs:86
  27: tokio::runtime::runtime::Runtime::block_on::hbb0651d31c14929d
      at /Users/cyril.fougeray/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/runtime.rs:350
  28: orb_mcu_util::main::h9479ae7912db7bc2
      at /Users/cyril.fougeray/Documents/worldcoin/orb-software/mcu-util/src/main.rs:202
  29: core::ops::function::FnOnce::call_once::h3951289dc03a5723
      at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/ops/function.rs:250
                                ⋮ 13 frames hidden ⋮

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
[====================] 100%
2024-06-14T07:13:34.488759Z  INFO orb_mcu_util::orb::security_board: ✅ Image integrity confirmed, activating image
```

2024-06-14 08:14 UTC, TheButlah commented
What does " the command might be targeted to the other MCU" mean?

2024-06-14 08:25 UTC, fouge commented
@TheButlah for example I want to reboot the security MCU, but the main MCU fails to respond: it doesn't make sense to fail

2024-06-14 16:45 UTC, TheButlah requested changes

2024-06-14 16:45 UTC, TheButlah commented on mcu-util/src/orb/main_board.rs
> +            });
You're producing an error just to immediately discard it.

I would rework this code to be something like:

```rust
        let ack_result = canfd_iface
            .send(McuPayload::ToMain(
                main_messaging::jetson_to_mcu::Payload::Heartbeat(
                    main_messaging::Heartbeat {
                        timeout_seconds: 0_u32,
                    },
                ),
            ))
            .await
            .map(|c| {
                if let CommonAckError::Success = c {
                    Ok(())
                } else {
                    Err(eyre!("ack error: {c}"))
                }
            });
      if let Err(e) = ack_result
           error!("Failed to send heartbeat to main mcu: {:#?}", e);
      });
```

2024-06-17 17:51 UTC, TheButlah commented on mcu-util/src/orb/main_board.rs
> +            });
I pushed a commit for this just now.

2024-06-17 17:51 UTC, TheButlah approved these changes

2024-06-17 17:56 UTC, TheButlah commented
I'm not entirely sure this is the right approach, but I am going to merge for now.

2024-06-17 17:59 UTC, merged