orb-ui: sound files in debian package
worldcoin/orb-software pull request #220
Opened 2024-09-12 12:06 UTC by fouge

ensure compatibility & correctness of the sound with a specific orb-ui binary.

2024-09-17 15:34 UTC, TheButlah requested changes
Lets use git lfs to store .wav files. This will avoid bloating the git history.

2024-09-17 16:11 UTC, fouge commented
@TheButlah this is what I did 🤔

2024-09-18 16:18 UTC, TheButlah commented
> @TheButlah this is what I did 🤔
The .gitattributes path was not right, so they didn't get tracked.

I've force pushed and fixed it, will merge in a sec.

2024-09-18 16:25 UTC, TheButlah approved these changes

2024-09-18 16:26 UTC, merged