hil: Use multi-part download for hil
worldcoin/orb-software pull request #253
Opened 2024-10-09 09:44 UTC by AlexKaravaev

AWS rust sdk is slow compared to cli, multipart download can speedup the process significantly,
see https://github.com/awslabs/aws-sdk-rust/discussions/1024. 

The logic for the change is mostly adapted from: https://github.com/smithy-lang/smithy-rs/blob/main/aws/sdk/benchmarks/s3-throughput/benchmark/src/multipart_get.rs.

For me the speedup was around 2x in Munich.

To be noted, that requests to s3 do cost something, but as I understood it's insignificant amount: https://aws.amazon.com/s3/pricing/?p=pm&c=s3&z=4

0.0004 $ per 1000 requests and with multi-part download we have ~40 requests per GB.

2024-10-09 15:32 UTC, TheButlah requested changes
Awesome! I didn't know about the multi-part downloads, TIL.

Excited to land this :)

2024-10-09 16:12 UTC, AlexKaravaev commented on hil/src/download_s3.rs
> +}
Everything in your comments makes sense. I rather lazely took the linked in the description upstream aws sdk code and just made it work. Will address the comments.

2024-10-14 20:48 UTC, TheButlah commented on hil/src/download_s3.rs
> +                let range = match range_option {
prefer let .. else syntax for simple pattern matching where the failure case evaluates to `!` (such as when doing `return` or `break`).

2024-10-14 20:49 UTC, TheButlah requested changes
1 tiny remaining change (the let .. else) and it will be good to go.

2024-10-15 14:11 UTC, merged